#pragma once

#include <format>
#include <string>
#include <string_view>

#include <tiny-orm/schema.hxx>

namespace tiny_orm {

    /**
     * The parts of SQL that differ between database engines.
     *
     * Deliberately small. BEGIN, COMMIT, ROLLBACK and LIMIT/OFFSET are identical
     * across the engines targeted here, so they are not abstracted -- adding them
     * before a backend needs them would be speculation.
     *
     * A connection owns its dialect, since driver and dialect always travel
     * together, and `DAO` passes it to the generators so application code never
     * mentions one.
     */
    class dialect {
    public:
        dialect() = default;
        dialect(dialect const&) = delete;
        auto operator=(dialect const&) -> dialect& = delete;
        virtual ~dialect() = default;

        [[nodiscard]] virtual auto name() const -> std::string_view = 0;

        /// Wraps an identifier: `"x"` in standard SQL, backticks in MySQL.
        [[nodiscard]] virtual auto quote(std::string_view identifier) const -> std::string = 0;

        /// The n-th bound parameter, 1-based: `$1` for PostgreSQL, `?` for SQLite.
        [[nodiscard]] virtual auto placeholder(int n) const -> std::string = 0;

        /// Renders a canonical column type.
        [[nodiscard]] virtual auto type_name(type_kind k) const -> std::string_view = 0;

        /// The clause marking a column as server-generated; empty when the engine
        /// needs no keyword.
        [[nodiscard]] virtual auto identity_clause() const -> std::string_view = 0;

        /// Whether INSERT ... RETURNING works. When false, a generated key has to
        /// be fetched by a second query.
        [[nodiscard]] virtual bool supports_returning() const = 0;

        /// Fetches the key generated by the last INSERT on this connection.
        /// Only consulted when `supports_returning()` is false.
        [[nodiscard]] virtual auto last_insert_id_sql() const -> std::string_view = 0;

        /**
         * Whether DROP TABLE accepts CASCADE.
         *
         * PostgreSQL uses it to drop dependent constraints along with the table;
         * SQLite rejects the keyword outright. `drop_table_sql` omits it where it
         * is unsupported rather than failing, since the engines that lack it also
         * do not need it.
         */
        [[nodiscard]] virtual bool supports_drop_cascade() const = 0;

        /**
         * The most bound parameters one statement may carry.
         *
         * The eighth thing that genuinely differs, and unlike the rest it affects
         * correctness rather than syntax: exceed it and the server rejects the
         * statement outright. Bulk insert divides this by the row width to decide
         * how many rows fit in one round trip.
         */
        [[nodiscard]] virtual auto max_bind_params() const -> int = 0;

        /**
         * Whether a raw `Column{.sql_type = "..."}` override names an integer type.
         *
         * Heuristic, and used only to validate `auto_increment`. The compile-time
         * check in the DDL generator covers columns whose type was derived; this
         * covers the ones where the user overrode it.
         */
        [[nodiscard]] virtual bool is_integral_type(std::string_view raw) const = 0;

        /// The rendered type for a column: the raw override when given, else `kind`.
        [[nodiscard]] auto type_for(column_info const& c) const -> std::string_view {
            return c.sql_type.empty() ? type_name(c.kind) : c.sql_type.view();
        }

        /// Whether this column may carry an identity clause.
        [[nodiscard]] bool allows_identity(column_info const& c) const {
            return c.sql_type.empty() ? detail::is_integral_kind(c.kind)
                                      : is_integral_type(c.sql_type.view());
        }
    };

} // namespace tiny_orm
