#pragma once

/**
 * PostgreSQL backend, over libpq.
 *
 * Compiled only when CMake found libpq; `TINY_ORM_HAS_POSTGRES` is defined by the
 * build in that case. Everything else in the framework, including the whole unit
 * test suite, works without it.
 */
#include <cstdlib>
#include <string>
#include <vector>

#include <tiny-orm/connection.hxx>
#include <tiny-orm/dialect.hxx>

#ifdef TINY_ORM_HAS_POSTGRES
#include <libpq-fe.h>
#endif

namespace tiny_orm {

    /// Deliberately outside the libpq guard: rendering PostgreSQL SQL needs no
    /// client library, so tests can assert on this dialect anywhere.
    class psql_dialect final : public dialect {
    public:
        [[nodiscard]] auto name() const -> std::string_view override { return "postgresql"; }

        [[nodiscard]] auto quote(std::string_view id) const -> std::string override {
            return std::format("\"{}\"", id);
        }
        [[nodiscard]] auto placeholder(int n) const -> std::string override {
            return std::format("${}", n);
        }

        [[nodiscard]] auto type_name(type_kind k) const -> std::string_view override {
            switch (k) {
                case type_kind::boolean: return "BOOLEAN";
                case type_kind::int16: return "SMALLINT";
                case type_kind::int32: return "INTEGER";
                case type_kind::int64: return "BIGINT";
                case type_kind::float32: return "REAL";
                case type_kind::float64: return "DOUBLE PRECISION";
                case type_kind::text: return "TEXT";
                // Without a time zone: values are UTC by convention and the
                // framework never converts, so TIMESTAMPTZ's session-dependent
                // output would only make the round trip non-deterministic.
                case type_kind::timestamp: return "TIMESTAMP";
            }
            return "TEXT";
        }

        [[nodiscard]] auto identity_clause() const -> std::string_view override {
            return "GENERATED BY DEFAULT AS IDENTITY";
        }
        [[nodiscard]] bool supports_returning() const override { return true; }
        [[nodiscard]] auto last_insert_id_sql() const -> std::string_view override { return {}; }

        [[nodiscard]] bool supports_drop_cascade() const override { return true; }

        /// The wire protocol counts parameters in an unsigned 16-bit field.
        [[nodiscard]] auto max_bind_params() const -> int override { return 65535; }

        [[nodiscard]] bool is_integral_type(std::string_view raw) const override {
            for (auto const* known : {"SMALLINT", "INTEGER", "INT", "INT2", "INT4", "INT8",
                                      "BIGINT", "SERIAL", "SMALLSERIAL", "BIGSERIAL"})
                if (raw == known) return true;
            return false;
        }
    };

#ifdef TINY_ORM_HAS_POSTGRES

    namespace detail {

        /// RAII for a PGresult, which PQclear must free on every path.
        class psql_result {
            PGresult* raw_ = nullptr;

        public:
            explicit psql_result(PGresult* raw) : raw_{raw} {}
            psql_result(psql_result const&) = delete;
            auto operator=(psql_result const&) -> psql_result& = delete;
            ~psql_result() {
                if (raw_ != nullptr) PQclear(raw_);
            }
            [[nodiscard]] auto get() const -> PGresult* { return raw_; }
        };

    } // namespace detail

    /**
     * A connection over libpq.
     *
     * `statement` is already exactly PQexecParams' shape -- SQL carrying $1..$n, an
     * array of parameter values as text, and NULL as a null pointer -- so binding is
     * a direct translation rather than an adaptation. Results are requested in text
     * format for the same reason.
     */
    class psql_connection final : public connection {
        PGconn* conn_ = nullptr;
        psql_dialect dialect_{};

    public:
        explicit psql_connection(std::string const& url) {
            conn_ = PQconnectdb(url.c_str());
            if (PQstatus(conn_) != CONNECTION_OK) {
                auto message = std::string{PQerrorMessage(conn_)};
                PQfinish(conn_);
                conn_ = nullptr;
                throw db_error{"tiny-orm: cannot connect to PostgreSQL: " + message};
            }
        }

        ~psql_connection() override {
            if (conn_ != nullptr) PQfinish(conn_);
        }

        [[nodiscard]] auto sql_dialect() const -> dialect const& override { return dialect_; }

        auto execute(statement const& s) -> result_set override {
            auto values = std::vector<char const*>{};
            values.reserve(s.params.size());
            for (auto const& p : s.params) values.push_back(p ? p->c_str() : nullptr);

            auto const res = detail::psql_result{PQexecParams(conn_, s.sql.c_str(),
                                                              static_cast<int>(values.size()),
                                                              nullptr, values.data(), nullptr,
                                                              nullptr, 0 /* text results */)};
            switch (PQresultStatus(res.get())) {
                case PGRES_TUPLES_OK: return to_result_set(res.get());
                case PGRES_COMMAND_OK: return result_set::affected(std::atol(PQcmdTuples(res.get())));
                default:
                    throw db_error{std::string{"tiny-orm: "} + PQresultErrorMessage(res.get())
                                   + "  [sql: " + s.sql + "]"};
            }
        }

        using connection::execute;

    private:
        static auto to_result_set(PGresult* res) -> result_set {
            auto const fields = PQnfields(res);
            auto const tuples = PQntuples(res);

            auto columns = std::vector<std::string>{};
            columns.reserve(static_cast<std::size_t>(fields));
            for (auto f = 0; f < fields; ++f) columns.emplace_back(PQfname(res, f));

            auto rows = std::vector<std::vector<cell>>{};
            rows.reserve(static_cast<std::size_t>(tuples));
            for (auto t = 0; t < tuples; ++t) {
                auto row = std::vector<cell>{};
                row.reserve(static_cast<std::size_t>(fields));
                for (auto f = 0; f < fields; ++f) {
                    // PQgetisnull is what keeps SQL NULL distinct from the empty
                    // string: PQgetvalue returns "" for both.
                    if (PQgetisnull(res, t, f) != 0) row.emplace_back();
                    else row.emplace_back(PQgetvalue(res, t, f));
                }
                rows.push_back(std::move(row));
            }
            return result_set::of(std::move(columns), std::move(rows));
        }
    };

#endif // TINY_ORM_HAS_POSTGRES

} // namespace tiny_orm
