#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_string.hpp>

#include <tiny-orm/ddl.hxx>
#include <tiny-orm/psql.hxx>

#include "model.hxx"

using Catch::Matchers::ContainsSubstring;

static psql_dialect const pg{};

TEST_CASE("CREATE TABLE renders every column", "[ddl]") {
    auto const sql = create_table_sql<Account>(pg);
    CHECK_THAT(sql, ContainsSubstring(R"(CREATE TABLE IF NOT EXISTS "bank_accounts")"));
    CHECK_THAT(sql, ContainsSubstring(R"("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL)"));
    CHECK_THAT(sql, ContainsSubstring(R"("owner" TEXT NOT NULL)"));
    CHECK_THAT(sql, ContainsSubstring(R"("nick_name" TEXT,)")); // nullable: no NOT NULL
    CHECK_THAT(sql, ContainsSubstring(R"(PRIMARY KEY ("id"))"));
}

TEST_CASE("foreign keys become named table-level constraints", "[ddl]") {
    auto const sql = create_table_sql<Transaction>(pg);
    CHECK_THAT(sql, ContainsSubstring(R"(CONSTRAINT "fk_transactions_account_id")"));
    CHECK_THAT(sql, ContainsSubstring(R"(FOREIGN KEY ("account_id") REFERENCES "bank_accounts" ("id"))"));
    CHECK_THAT(sql, ContainsSubstring("ON DELETE CASCADE"));
}

TEST_CASE("ddl options switch off quoting and IF NOT EXISTS", "[ddl]") {
    auto const sql = create_table_sql<Account>(pg, {.if_not_exists = false, .quote_identifiers = false});
    CHECK_THAT(sql, ContainsSubstring("CREATE TABLE bank_accounts ("));
    CHECK_THAT(sql, !ContainsSubstring("\""));
}

TEST_CASE("DROP TABLE honours its options", "[ddl]") {
    CHECK(drop_table_sql<Account>(pg) == R"(DROP TABLE IF EXISTS "bank_accounts";)");
    CHECK(drop_table_sql<Account>(pg, {.cascade = true}) == R"(DROP TABLE IF EXISTS "bank_accounts" CASCADE;)");
    CHECK(drop_table_sql<Account>(pg, {.if_exists = false, .quote_identifiers = false}) ==
          "DROP TABLE bank_accounts;");
}
