#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_string.hpp>

#include <tiny-orm/ddl.hxx>
#include <tiny-orm/dml.hxx>
#include <tiny-orm/psql.hxx>
#include <tiny-orm/sqlite.hxx>

#include "model.hxx"

using Catch::Matchers::ContainsSubstring;

static psql_dialect const pg{};
static sqlite_dialect const lite{};

TEST_CASE("placeholders differ between engines", "[dialect]") {
    CHECK(pg.placeholder(1) == "$1");
    CHECK(pg.placeholder(3) == "$3");
    CHECK(lite.placeholder(1) == "?");
    CHECK(lite.placeholder(3) == "?"); // SQLite numbers them implicitly
}

TEST_CASE("canonical kinds render per engine", "[dialect]") {
    CHECK(pg.type_name(type_kind::int64) == "BIGINT");
    CHECK(lite.type_name(type_kind::int64) == "INTEGER");

    CHECK(pg.type_name(type_kind::float64) == "DOUBLE PRECISION");
    CHECK(lite.type_name(type_kind::float64) == "REAL");

    CHECK(pg.type_name(type_kind::boolean) == "BOOLEAN");
    CHECK(lite.type_name(type_kind::boolean) == "INTEGER"); // no native boolean
}

TEST_CASE("the same entity renders differently per engine", "[dialect]") {
    auto const pg_sql = create_table_sql<Account>(pg);
    auto const lite_sql = create_table_sql<Account>(lite);

    CHECK_THAT(pg_sql, ContainsSubstring(R"("balance" DOUBLE PRECISION NOT NULL)"));
    CHECK_THAT(lite_sql, ContainsSubstring(R"("balance" REAL NOT NULL)"));

    CHECK_THAT(pg_sql, ContainsSubstring("GENERATED BY DEFAULT AS IDENTITY"));
    // SQLite needs no keyword: INTEGER PRIMARY KEY already generates keys.
    CHECK_THAT(lite_sql, !ContainsSubstring("GENERATED"));
    CHECK_THAT(lite_sql, !ContainsSubstring("AUTOINCREMENT"));
}

TEST_CASE("DML placeholders follow the dialect", "[dialect]") {
    auto const a = Account{.id = 7, .ownerName = "Ada", .balance = 10.0};
    CHECK_THAT(update_by_object(a, pg).sql, ContainsSubstring(R"(WHERE "id" = $4)"));
    CHECK_THAT(update_by_object(a, lite).sql, ContainsSubstring(R"(WHERE "id" = ?)"));
}

TEST_CASE("a raw sql_type override is checked by the dialect, not the compiler", "[dialect]") {
    // Ledger's key is a plain long, so this passes the compile-time kind check and
    // reaches the dialect's is_integral_type.
    CHECK(pg.is_integral_type("BIGINT"));
    CHECK(pg.is_integral_type("BIGSERIAL"));
    CHECK_FALSE(pg.is_integral_type("TEXT"));
    CHECK(lite.is_integral_type("INTEGER"));
    CHECK_FALSE(lite.is_integral_type("BIGSERIAL")); // not a SQLite type
}

TEST_CASE("both engines support RETURNING", "[dialect]") {
    CHECK(pg.supports_returning());
    CHECK(lite.supports_returning());
    CHECK_THAT(insert_object(Account{}, pg).sql, ContainsSubstring(R"(RETURNING "id")"));
    CHECK_THAT(insert_object(Account{}, lite).sql, ContainsSubstring(R"(RETURNING "id")"));
}

TEST_CASE("DROP CASCADE is omitted where the engine rejects it", "[dialect]") {
    CHECK(pg.supports_drop_cascade());
    CHECK_FALSE(lite.supports_drop_cascade());

    CHECK(drop_table_sql<Account>(pg, {.cascade = true})
          == R"(DROP TABLE IF EXISTS "bank_accounts" CASCADE;)");
    CHECK(drop_table_sql<Account>(lite, {.cascade = true})
          == R"(DROP TABLE IF EXISTS "bank_accounts";)");
}
